// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  LetDef = 2,
  VariableName = 3,
  _let = 4,
  LambdaExpr = 6,
  Lambda = 7,
  Dot = 8,
  IfExpr = 9,
  _if = 10,
  then = 11,
  _else = 12,
  Application = 13,
  Number = 14,
  ParenExpr = 17,
  Operator = 18
