// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_VariableName = {__proto__:null,let:8, if:20, then:22, else:24}
export const parser = LRParser.deserialize({
  version: 14,
  states: "%vQVQPOOOOQO'#Co'#CoQVQPOOOnQPO'#CbOsQPO'#CmOOQO'#Cz'#CzOOQO'#Cp'#CpO!UQPO'#CiO!sQPO'#CyOOQO'#Cx'#CxOOQO'#Cw'#CwQiQPOOOsQPO'#CeO#XQPO'#C^OOQO-E6m-E6mO#^QPO,58|O#cQPO,59XOOQO-E6n-E6nO#hQPO'#CqO#sQPO,59eQVQPO'#CrQiQPOOO$XQPO,59PO$^QPO,58xOsQPO1G.hOOQO1G.s1G.sOOQO,59],59]OOQO-E6o-E6oOOQO,59^,59^OOQO-E6p-E6pOsQPO1G.kOsQPO1G.dOOQO7+$S7+$SO$cQPO7+$VOOQO7+$O7+$OOsQPO<<GqOOQOAN=]AN=]",
  stateData: "$k~OiOS~ORTOS]OVROY[O^TO`SOjPO~OR_O~ORTOVROY[O^TO`SO~ORTO^TO`SOb]Xg]Xj]X_]XZ]X[]X~ObbOgmXjmX_mXZmX[mX~ORgO~OWhO~O_iO~ORTO^TO`SO~ObbOgmajma_maZma[ma~OZnO~OToO~O[sO~O^R~",
  goto: "$boPPpPPPuPPuPPP!QPPP!`P!m!x#X#_PPPP#e#lu$TVYOQdcXOQS[dhnosbWOQS[dhnosRjbgTOQSV[bdhnosQQOS^QdTdZedVOQS[bdhnosRaVQcWRkcQeZRmeSZOQRldUYOQdQ`SQf[QphQqnQroRtsgUOQSV[bdhnos",
  nodeNames: "⚠ Program LetDef VariableName let = LambdaExpr Lambda Dot IfExpr if then else Application Number ) ( ParenExpr Operator",
  maxTerm: 30,
  nodeProps: [
    ["openedBy", 15,"("],
    ["closedBy", 16,")"]
  ],
  skippedNodes: [0],
  repeatNodeCount: 4,
  tokenData: "#q~R`XY!TYZ!c]^!Tpq!Txy!hyz!m{|!r}!O!r!O!P!w!Q![!|!_!`#U!c!}#Z#O#P#l#R#S#Z#T#o#Z5s5t#l~!YRi~XY!T]^!Tpq!T~!hOj~~!mO`~~!rO_~~!wOb~~!|OW~~#RP^~!Q![!|~#ZOT~~#`SR~!Q![#Z!c!}#Z#R#S#Z#T#o#Z~#qOV~",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  specialized: [{term: 3, get: (value) => spec_VariableName[value] || -1}],
  tokenPrec: 162
})
